### ISSUE TITLE
Error while training with IAM dataset

### ISSUE THREAD

**Issue by AlxJude** [herobd/handwriting_line_generation#15]
Really appreciate the great work you have done.

I'm trying to train the generator with IAM dataset and I'm getting the following error.

```
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main(config, args.resume)
  File "train.py", line 63, in main
    trainer = trainerClass(model, loss, metrics,
  File "handwriting_line_generation/trainer/hw_with_style_trainer.py", line 115, in __init__
    self.text_data = TextData(config['trainer']['text_data'],config['data_loader']['char_file'],text_data_batch_size,max_len=text_data_max_len,words=text_words,characterBalance=characterBalance) if 'text_data' in config['trainer'] else None
  File "handwriting_line_generation/datasets/text_data.py", line 15, in __init__
    with open(textfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/english_text.txt'
```

Thank you for your help.

**Comment by herobd** [comment]
The `english_text.txt` is just an example text file. Really any text corpus should do.
See **https://github.com/herobd/handwriting_line_generation/issues/3**

**Comment by AlxJude** [comment]
Thank you so much for the reference. It helped!
