### ISSUE TITLE
Error training the generator with IAM

### ISSUE THREAD

**Issue by AlxJude** [herobd/handwriting_line_generation#17]
Hello again, 

While training the generator with IAM daaset, I am getting the following error.

```
Begin training
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main(config, args.resume)
  File "train.py", line 79, in main
    trainer.train()
  File "/handwriting_line_generation/base/base_trainer.py", line 219, in train
    result = self._train_iteration(self.iteration)
  File "/handwriting_line_generation/trainer/hw_with_style_trainer.py", line 367, in _train_iteration
    losses = self.run_gen(instance,lesson)
  File "/handwriting_line_generation/trainer/hw_with_style_trainer.py", line 1069, in run_gen
    recon,style = self.model.autoencode(image,label,mask,a_batch_size,center_line=center_line,stop_grad_extractor=autoSGStyle)
  File "/handwriting_line_generation/model/hw_with_style.py", line 729, in autoencode
    style = self.extract_style(image,label,a_batch_size)
  File "/handwriting_line_generation/model/hw_with_style.py", line 781, in extract_style
    style = self.style_extractor(collapsed_image, collapsed_label)
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/handwriting_line_generation/model/char_style.py", line 122, in forward
    x = self.down(x)
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/handwriting_line_generation/model/MUNIT_networks.py", line 1124, in forward
    x = self.conv(self.pad(x))
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/modules/padding.py", line 275, in forward
    return F.pad(input, self.padding, 'replicate')
  File "/anaconda3/envs/DocumentAnalysis/lib/python3.8/site-packages/torch/nn/functional.py", line 4172, in _pad
    return torch._C._nn.replication_pad2d(input, pad)
RuntimeError: "replication_pad2d_cuda" not implemented for 'Long'
```

Before this error I got the first error in #11 , which I solved as per the suggestion in the post.

Kindly help me with this error.
Thank you for your help.

**Comment by Tytskiy** [comment]
Hello! 
I fix this by adding  `x = x.float() `  in body this function:
https://github.com/herobd/handwriting_line_generation/blob/d09994d9ca6d39a81a2132921dc9d02092b1332e/model/autoencoder.py#L62-L67

pytorch=1.7.1
cudatoolkit=10.1

**Comment by Tytskiy** [comment]
If you mean training encoder.py, then may use `x = x.float()`
Its work for me. I add this in function
https://github.com/herobd/handwriting_line_generation/blob/d09994d9ca6d39a81a2132921dc9d02092b1332e/model/autoencoder.py#L62-L67

pytorch = 1.7.1
cudatoolkit=10.1

**Comment by herobd** [comment]
I was relying on a default tensor type in the dataset collate. I just fixed this, so pull the latest.

**Comment by AlxJude** [comment]
It is working smoothly now. Thanks!
