### ISSUE TITLE
Issue with generate image from your checkpoint

### ISSUE THREAD

**Issue by theravikumar** [herobd/handwriting_line_generation#28]
Hi, Great work. I was searching for generating handwritten text which looks very similar to human and I found your repo. I tried to use it but I am getting error of xml. Do i have to train it on my system.

python generate.py -c /home/ravi/Downloads/RIMES_weights/RIME_weights/RIMESLines_hwr_cnnOnly_batchnorm_aug/checkpoint-iteration425000.pth -d /home/ravi/Downloads/Output
loaded iteration 425000
Traceback (most recent call last):
  File "/home/ravi/Downloads/handwriting_line_generation-master/generate.py", line 906, in <module>
    main(args.checkpoint, args.savedir, gpu=args.gpu,  config=args.config, addToConfig=addtoconfig, test =args.test,arguments=arguments, style_loc=args.style_loc)
  File "/home/ravi/Downloads/handwriting_line_generation-master/generate.py", line 139, in main
    data_loader, valid_data_loader = getDataLoader(config,'train')
  File "/home/ravi/Downloads/handwriting_line_generation-master/data_loader/data_loaders.py", line 39, in getDataLoader
    return withCollate(author_rimeslines_dataset.AuthorRIMESLinesDataset,author_rimeslines_dataset.collate,batch_size,valid_batch_size,shuffle,shuffleValid,numDataWorkers,split,data_dir,config)
  File "/home/ravi/Downloads/handwriting_line_generation-master/data_loader/data_loaders.py", line 64, in withCollate
    trainData = setObj(dirPath=data_dir, split='train', config=config['data_loader'])
  File "/home/ravi/Downloads/handwriting_line_generation-master/datasets/author_rimeslines_dataset.py", line 145, in __init__
    self.authors = parseXML(xml)
  File "/home/ravi/Downloads/handwriting_line_generation-master/utils/parseRIMESlines.py", line 13, in getLineBoundaries
    tree = ET.parse(xmlPath)
  File "/home/ravi/anaconda3/envs/hgn/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/home/ravi/anaconda3/envs/hgn/lib/python3.9/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../data/RIMES/lines_training_2011.xml'

**Comment by herobd** [comment]
First, you're using the wrong snapshot, that one is the the handwritting recognizer, you want the `RIMESLinesslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG/checkpoint-iteration175000.pth` snapshot to generate.

The missing XML is part the RIMES dataset. You don't actually need it to generate if your using example images for the style (`from-to` option in `generate.py`) or loading styles via the pickle (`-s RIME_weights/RIMESLinesslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMGtest_styles_175000.pkl`), so I've changed the code to make the loading of the dataset lazy.
Pull the latest and it should work.

**Comment by theravikumar** [comment]
Thank you very much. It worked like charm.
