### ISSUE TITLE
Wrong generated text

### ISSUE THREAD

**Issue by huynhtruc0309** [herobd/handwriting_line_generation#9]
I ran the pretrain model on RIMES dataset by this command.
```
python generate.py -c ../RIME_weights/RIMESLinesslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG/checkpoint-iteration175000.pth -d output -f configs/cf_RIMESLinesslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG.json
```
Next, I tried all the generate options. Sometimes I got this error:
```
File "/media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/handwriting_line_generation/model/hw_with_style.py", line 845, in insert_spaces
    spaced[i,b,cls]=1
IndexError: index 80 is out of bounds for dimension 2 with size 78
```
Sometimes I got the generated handwriting but they look very weird, noisy and not text.

I don't know where I got wrong :(

**Comment by herobd** [comment]
The error is caused by trying to have the model create a character outside of it character set. I realized I forgot to include my RIMES character set. I've added it and changed `cf_RIMESLinesslant_noMask_charSpecSingleAppend_GANMedMT_autoAEMoPrcp2tightNewCTCUseGen_balB_hCF0.75_sMG.json` to point to it. Try it now.

**Comment by huynhtruc0309** [comment]
Another problem. I continued to run but it got stuck here and nothing generated. I used CPU.
```
indexes/random interp/vae random/strech/author display/math/turk gen/from-to/umap-images/Random styles/help/quit? h
Options:
[a] show author ids
[r] random interpolation: selects n styles (dataset extracted) and interpolated between them in a circlular pattern
[v] same as above, but styles are randomly sampled from guassian distribution (for VAE)
[s] strech: manipulate the 1d text encoding to interpolate horizontal streching
[m] vector math: perform vector math with style vectors. Use "+" and "-". Use author id to specifiy vector, and [id1,id2,...] to average vectors together.
[t] MTurk gen: routine used to generate data for MTurk experimenet
[R] Random: generate n images using random (interpolated) styles. Can use fixed or random text
[f] Given two image paths, interpolate from one style to the other using the given text.
indexes/random interp/vae random/strech/author display/math/turk gen/from-to/umap-images/Random styles/help/quit? r
number of styles? 3
step (0.1 is normal)? 0.1
text? 123
i: 11, a: eval2011-2.png
/media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/handwriting_line_generation/model/char_style.py:143: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370141920/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  horz_cents = locs[b].nonzero() #x locations of each instance of char_n
next index: 52
i: 52, a: eval2011-10.png
next index: 98
```

**Comment by herobd** [comment]
When you say "it got stuck", do you mean the program freezes? Generally, I was able to run it on CPU without an issue. Try using the `f` option and just provide it two images (should be faster). Also be sure the output directory exists, it doesn't check for that.

**Comment by huynhtruc0309** [comment]
1) Yes, the program freezes. It works fine with f option. And I also checked the output directory. Can you guess where the problem comes from?

2) And there's also the problem when generating texts that have spaces.
```
indexes/random interp/vae random/strech/author display/math/turk gen/from-to/umap-images/Random styles/help/quit? f
image path 1? /media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/data/img3.png
image path 2? /media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/data/img4.png     
text to generate? who am i?
/media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/handwriting_line_generation/model/char_style.py:143: UserWarning: This overload of nonzero is deprecated:
        nonzero()
Consider using one of the following signatures instead:
        nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:766.)
  horz_cents = locs[b].nonzero() #x locations of each instance of char_n
Traceback (most recent call last):
  File "generate.py", line 906, in <module>
    main(args.checkpoint, args.savedir, gpu=args.gpu,  config=args.config, addToConfig=addtoconfig, test =args.test,arguments=arguments, style_loc=args.style_loc)
  File "generate.py", line 629, in main
    images,stylesInter=interpolate(model,style1,style2, text_gen,char_to_idx,gpu)
  File "generate.py", line 763, in interpolate
    gen = model(label,label_len,style,flat=True)
  File "/home/huynhtruc0309/anaconda3/envs/truchlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/handwriting_line_generation/model/hw_with_style.py", line 677, in forward
    spaced, padded = self.insert_spaces(label,label_lengths,self.counts)
  File "/media/huynhtruc0309/DATA/vtcc/generate_vietnamese_htr/handwriting_line_generation/model/hw_with_style.py", line 833, in insert_spaces
    count = round(np.random.normal(counts[i,b,0].item(),self.count_std))
IndexError: index 8 is out of bounds for dimension 0 with size 8
```
Thank you very much for helping me.
